install:
  - echo "Nothing"

script:
  - docker build -t fundrequestio/keycloak:"$TRAVIS_BRANCH" .

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push fundrequestio/keycloak:"$TRAVIS_BRANCH"